/**
 * Catálogo de principales ciudades y municipios de Colombia agrupados por departamento
 * para autocompletado y selección en formularios públicos.
 */
export const MUNICIPIOS_COLOMBIA: string[] = [
  // Principales y Capitales
  'Bogotá D.C. (Cundinamarca)',
  'Medellín (Antioquia)',
  'Cali (Valle del Cauca)',
  'Barranquilla (Atlántico)',
  'Cartagena (Bolívar)',
  'Bucaramanga (Santander)',
  'Cúcuta (Norte de Santander)',
  'Pereira (Risaralda)',
  'Santa Marta (Magdalena)',
  'Ibagué (Tolima)',
  'Pasto (Nariño)',
  'Manizales (Caldas)',
  'Neiva (Huila)',
  'Villavicencio (Meta)',
  'Armenia (Quindío)',
  'Valledupar (Cesar)',
  'Montería (Córdoba)',
  'Sincelejo (Sucre)',
  'Popayán (Cauca)',
  'Tunja (Boyacá)',
  'Riohacha (La Guajira)',
  'Florencia (Caquetá)',
  'Quibdó (Chocó)',
  'Yopal (Casanare)',
  'Leticia (Amazonas)',
  'Arauca (Arauca)',
  'Inírida (Guainía)',
  'San José del Guaviare (Guaviare)',
  'Mitú (Vaupés)',
  'Puerto Carreño (Vichada)',
  'Mocoa (Putumayo)',
  'San Andrés Isla (San Andrés y Providencia)',

  // Antioquia
  'Apartadó (Antioquia)',
  'Bello (Antioquia)',
  'Caldas (Antioquia)',
  'Carepa (Antioquia)',
  'Caucasia (Antioquia)',
  'Chigorodó (Antioquia)',
  'Copacabana (Antioquia)',
  'El Bagre (Antioquia)',
  'El Carmen de Viboral (Antioquia)',
  'El Retiro (Antioquia)',
  'El Santuario (Antioquia)',
  'Envigado (Antioquia)',
  'Girardota (Antioquia)',
  'Guarne (Antioquia)',
  'Itagüí (Antioquia)',
  'La Ceja (Antioquia)',
  'La Estrella (Antioquia)',
  'Marinilla (Antioquia)',
  'Puerto Berrío (Antioquia)',
  'Rionegro (Antioquia)',
  'Sabaneta (Antioquia)',
  'Santa Bárbara (Antioquia)',
  'Santa Fe de Antioquia (Antioquia)',
  'Santa Rosa de Osos (Antioquia)',
  'Segovia (Antioquia)',
  'Turbo (Antioquia)',
  'Yarumal (Antioquia)',

  // Atlántico
  'Baranoa (Atlántico)',
  'Galapa (Atlántico)',
  'Malambo (Atlántico)',
  'Puerto Colombia (Atlántico)',
  'Sabanalarga (Atlántico)',
  'Sabanagrande (Atlántico)',
  'Soledad (Atlántico)',

  // Bolívar
  'Arjona (Bolívar)',
  'Carmen de Bolívar (Bolívar)',
  'Magangué (Bolívar)',
  'Mompós (Bolívar)',
  'Turbaco (Bolívar)',
  'Turbaná (Bolívar)',

  // Boyacá
  'Chiquinquirá (Boyacá)',
  'Duitama (Boyacá)',
  'Garagoa (Boyacá)',
  'Moniquirá (Boyacá)',
  'Nobsa (Boyacá)',
  'Paipa (Boyacá)',
  'Puerto Boyacá (Boyacá)',
  'Sogamoso (Boyacá)',
  'Villa de Leyva (Boyacá)',

  // Caldas
  'Anserma (Caldas)',
  'Chinchiná (Caldas)',
  'La Dorada (Caldas)',
  'Riosucio (Caldas)',
  'Salamina (Caldas)',
  'Villamaría (Caldas)',

  // Caquetá
  'San Vicente del Caguán (Caquetá)',

  // Casanare
  'Aguazul (Casanare)',
  'Paz de Ariporo (Casanare)',
  'Tauramena (Casanare)',
  'Villanueva (Casanare)',

  // Cauca
  'Guachené (Cauca)',
  'Patía - El Bordo (Cauca)',
  'Puerto Tejada (Cauca)',
  'Santander de Quilichao (Cauca)',

  // Cesar
  'Aguachica (Cesar)',
  'Agustín Codazzi (Cesar)',
  'Bosconia (Cesar)',
  'Curumaní (Cesar)',
  'La Jagua de Ibirico (Cesar)',
  'La Paz (Cesar)',

  // Córdoba
  'Cereté (Córdoba)',
  'Lorica (Córdoba)',
  'Montelíbano (Córdoba)',
  'Planeta Rica (Córdoba)',
  'Sahagún (Córdoba)',
  'Tierralta (Córdoba)',

  // Cundinamarca
  'Cajicá (Cundinamarca)',
  'Chia (Cundinamarca)',
  'Chocontá (Cundinamarca)',
  'Cota (Cundinamarca)',
  'El Rosal (Cundinamarca)',
  'Facatativá (Cundinamarca)',
  'Funza (Cundinamarca)',
  'Fusagasugá (Cundinamarca)',
  'Gachancipá (Cundinamarca)',
  'Girardot (Cundinamarca)',
  'Guaduas (Cundinamarca)',
  'La Calera (Cundinamarca)',
  'La Mesa (Cundinamarca)',
  'Madrid (Cundinamarca)',
  'Mosquera (Cundinamarca)',
  'Pacho (Cundinamarca)',
  'San Antonio del Tequendama (Cundinamarca)',
  'Sibaté (Cundinamarca)',
  'Silvania (Cundinamarca)',
  'Soacha (Cundinamarca)',
  'Sopó (Cundinamarca)',
  'Subachoque (Cundinamarca)',
  'Tabio (Cundinamarca)',
  'Tenjo (Cundinamarca)',
  'Tocancipá (Cundinamarca)',
  'Ubaté (Cundinamarca)',
  'Villeta (Cundinamarca)',
  'Zipaquirá (Cundinamarca)',

  // Huila
  'Campoalegre (Huila)',
  'Garzón (Huila)',
  'La Plata (Huila)',
  'Palermo (Huila)',
  'Pitalito (Huila)',
  'Rivera (Huila)',
  'San Agustín (Huila)',

  // La Guajira
  'Fonseca (La Guajira)',
  'Maicao (La Guajira)',
  'Manaure (La Guajira)',
  'San Juan del Cesar (La Guajira)',
  'Uribia (La Guajira)',
  'Villanueva (La Guajira)',

  // Magdalena
  'Aracataca (Magdalena)',
  'Ciénaga (Magdalena)',
  'El Banco (Magdalena)',
  'Fundación (Magdalena)',
  'Plato (Magdalena)',

  // Meta
  'Acacías (Meta)',
  'Cumaral (Meta)',
  'Granada (Meta)',
  'Guamal (Meta)',
  'Puerto Gaitán (Meta)',
  'Puerto López (Meta)',
  'Restrepo (Meta)',
  'San Martín (Meta)',

  // Nariño
  'Ipiales (Nariño)',
  'La Unión (Nariño)',
  'Sandoná (Nariño)',
  'Tumaco (Nariño)',
  'Túquerres (Nariño)',

  // Norte de Santander
  'Los Patios (Norte de Santander)',
  'Ocaña (Norte de Santander)',
  'Pamplona (Norte de Santander)',
  'Tibú (Norte de Santander)',
  'Villa del Rosario (Norte de Santander)',

  // Putumayo
  'Orito (Putumayo)',
  'Puerto Asís (Putumayo)',
  'Valle del Guamuez (Putumayo)',
  'Villagarzón (Putumayo)',

  // Quindío
  'Calarcá (Quindío)',
  'Circasia (Quindío)',
  'Filandia (Quindío)',
  'La Tebaida (Quindío)',
  'Montenegro (Quindío)',
  'Quimbaya (Quindío)',
  'Salento (Quindío)',

  // Risaralda
  'Dosquebradas (Risaralda)',
  'La Virginia (Risaralda)',
  'Santa Rosa de Cabal (Risaralda)',

  // Santander
  'Barbosa (Santander)',
  'Barrancabermeja (Santander)',
  'Charalá (Santander)',
  'Floridablanca (Santander)',
  'Girón (Santander)',
  'Málaga (Santander)',
  'Piedecuesta (Santander)',
  'Rionegro (Santander)',
  'San Gil (Santander)',
  'San Vicente de Chucurí (Santander)',
  'Socorro (Santander)',
  'Vélez (Santander)',

  // Sucre
  'Corozal (Sucre)',
  'San Marcos (Sucre)',
  'San Onofre (Sucre)',
  'Sampués (Sucre)',
  'Tolú (Sucre)',

  // Tolima
  'Chaparral (Tolima)',
  'Espinal (Tolima)',
  'Flandes (Tolima)',
  'Guamo (Tolima)',
  'Honda (Tolima)',
  'Lérida (Tolima)',
  'Líbano (Tolima)',
  'Mariquita (Tolima)',
  'Melgar (Tolima)',
  'Purificación (Tolima)',

  // Valle del Cauca
  'Alcalá (Valle del Cauca)',
  'Andalucía (Valle del Cauca)',
  'Ansermanuevo (Valle del Cauca)',
  'Buenaventura (Valle del Cauca)',
  'Buga / Guadalajara de Buga (Valle del Cauca)',
  'Bugalagrande (Valle del Cauca)',
  'Caicedonia (Valle del Cauca)',
  'Candelaria (Valle del Cauca)',
  'Cartago (Valle del Cauca)',
  'Dagua (Valle del Cauca)',
  'El Cerrito (Valle del Cauca)',
  'Florida (Valle del Cauca)',
  'Ginebra (Valle del Cauca)',
  'Guacarí (Valle del Cauca)',
  'Jamundí (Valle del Cauca)',
  'La Unión (Valle del Cauca)',
  'La Victoria (Valle del Cauca)',
  'Obando (Valle del Cauca)',
  'Palmira (Valle del Cauca)',
  'Pradera (Valle del Cauca)',
  'Restrepo (Valle del Cauca)',
  'Roldanillo (Valle del Cauca)',
  'San Pedro (Valle del Cauca)',
  'Sevilla (Valle del Cauca)',
  'Toro (Valle del Cauca)',
  'Trujillo (Valle del Cauca)',
  'Tuluá (Valle del Cauca)',
  'Ulloa (Valle del Cauca)',
  'Versalles (Valle del Cauca)',
  'Vijes (Valle del Cauca)',
  'Yotoco (Valle del Cauca)',
  'Yumbo (Valle del Cauca)',
  'Zarzal (Valle del Cauca)',
]
